### ISSUE TITLE
Cannot install in stellarmate os

### ISSUE THREAD

**Issue by thaiacepilot** [iMhack/indi_cam90_ccd#2]
cd libftdi
git clone git://developer.intra2net.com/libftdi
cd libftdi
mkdir build
cd build
cmake .. 
then got error
`-- The C compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type: RelWithDebInfo
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Checking for module 'libusb-1.0'
--   No package 'libusb-1.0' found
-- Could NOT find LIBUSB (missing: LIBUSB_LIBRARIES LIBUSB_INCLUDE_DIR) 
-- Detected git snapshot version: v1.4-37-gafd738f
-- Found Confuse: /usr/lib/arm-linux-gnueabihf/libconfuse.so  
-- Looking for dgettext
-- Looking for dgettext - found
-- Found Libintl: /usr/include  
-- Building ftdi_eeprom
-- Summary of build options:

  Build static libs: ON
  Build C++ bindings: OFF
  Build Python bindings: OFF
  Build ftdi_eeprom: ON
  Build examples: ON
  Build tests: OFF
  Build API documentation: OFF

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBUSB_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/stellarmate/libftdi/libftdi
   used as include directory in directory /home/stellarmate/libftdi/libftdi
   used as include directory in directory /home/stellarmate/libftdi/libftdi
   used as include directory in directory /home/stellarmate/libftdi/libftdi
   used as include directory in directory /home/stellarmate/libftdi/libftdi
   used as include directory in directory /home/stellarmate/libftdi/libftdi
   used as include directory in directory /home/stellarmate/libftdi/libftdi
   used as include directory in directory /home/stellarmate/libftdi/libftdi
   used as include directory in directory /home/stellarmate/libftdi/libftdi
   used as include directory in directory /home/stellarmate/libftdi/libftdi/src
   used as include directory in directory /home/stellarmate/libftdi/libftdi/src
   used as include directory in directory /home/stellarmate/libftdi/libftdi/src
   used as include directory in directory /home/stellarmate/libftdi/libftdi/src
   used as include directory in directory /home/stellarmate/libftdi/libftdi/src
   used as include directory in directory /home/stellarmate/libftdi/libftdi/src
   used as include directory in directory /home/stellarmate/libftdi/libftdi/src
   used as include directory in directory /home/stellarmate/libftdi/libftdi/src
   used as include directory in directory /home/stellarmate/libftdi/libftdi/src
   used as include directory in directory /home/stellarmate/libftdi/libftdi/src
   used as include directory in directory /home/stellarmate/libftdi/libftdi/ftdi_eeprom
   used as include directory in directory /home/stellarmate/libftdi/libftdi/ftdi_eeprom
   used as include directory in directory /home/stellarmate/libftdi/libftdi/ftdi_eeprom
   used as include directory in directory /home/stellarmate/libftdi/libftdi/ftdi_eeprom
   used as include directory in directory /home/stellarmate/libftdi/libftdi/ftdi_eeprom
   used as include directory in directory /home/stellarmate/libftdi/libftdi/ftdi_eeprom
   used as include directory in directory /home/stellarmate/libftdi/libftdi/ftdi_eeprom
   used as include directory in directory /home/stellarmate/libftdi/libftdi/ftdi_eeprom
   used as include directory in directory /home/stellarmate/libftdi/libftdi/ftdi_eeprom
   used as include directory in directory /home/stellarmate/libftdi/libftdi/examples
   used as include directory in directory /home/stellarmate/libftdi/libftdi/examples
   used as include directory in directory /home/stellarmate/libftdi/libftdi/examples
   used as include directory in directory /home/stellarmate/libftdi/libftdi/examples
   used as include directory in directory /home/stellarmate/libftdi/libftdi/examples
   used as include directory in directory /home/stellarmate/libftdi/libftdi/examples
   used as include directory in directory /home/stellarmate/libftdi/libftdi/examples
   used as include directory in directory /home/stellarmate/libftdi/libftdi/examples
   used as include directory in directory /home/stellarmate/libftdi/libftdi/examples
   used as include directory in directory /home/stellarmate/libftdi/libftdi/examples
   used as include directory in directory /home/stellarmate/libftdi/libftdi/examples
   used as include directory in directory /home/stellarmate/libftdi/libftdi/examples
   used as include directory in directory /home/stellarmate/libftdi/libftdi/examples
   used as include directory in directory /home/stellarmate/libftdi/libftdi/examples
   used as include directory in directory /home/stellarmate/libftdi/libftdi/examples
   used as include directory in directory /home/stellarmate/libftdi/libftdi/examples
   used as include directory in directory /home/stellarmate/libftdi/libftdi/examples
   used as include directory in directory /home/stellarmate/libftdi/libftdi/examples
   used as include directory in directory /home/stellarmate/libftdi/libftdi/examples
   used as include directory in directory /home/stellarmate/libftdi/libftdi/examples
   used as include directory in directory /home/stellarmate/libftdi/libftdi/packages
   used as include directory in directory /home/stellarmate/libftdi/libftdi/packages
   used as include directory in directory /home/stellarmate/libftdi/libftdi/packages
   used as include directory in directory /home/stellarmate/libftdi/libftdi/packages
   used as include directory in directory /home/stellarmate/libftdi/libftdi/packages
   used as include directory in directory /home/stellarmate/libftdi/libftdi/packages
   used as include directory in directory /home/stellarmate/libftdi/libftdi/packages
   used as include directory in directory /home/stellarmate/libftdi/libftdi/packages
LIBUSB_LIBRARIES (ADVANCED)
    linked by target "ftdi1-static" in directory /home/stellarmate/libftdi/libftdi/src
    linked by target "ftdi1" in directory /home/stellarmate/libftdi/libftdi/src

-- Configuring incomplete, errors occurred!
See also "/home/stellarmate/libftdi/libftdi/build/CMakeFiles/CMakeOutput.log".`

**Comment by gehelem** [comment]
it looks like libsub development libraries are missing
you should try to install them :
`sudo apt install libusb-dev`

**Comment by thaiacepilot** [comment]
Stellarmate support has update with DIY CCD support now!
